import type { Metadata } from "next";

/**
 * One place that knows the site's own identity. Before this, the origin was
 * re-derived with the same `||` fallback in layout.tsx, sitemap.ts and
 * robots.ts — three chances to drift, and a canonical URL that disagrees with
 * the sitemap is worse than having neither.
 */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(
  /\/+$/,
  "",
);

export const SITE_NAME = "UFTECH.AI";

/**
 * Name, address and phone, written once. Search engines corroborate a business
 * by matching these across the site, the knowledge panel and third-party
 * directories, so every surface that prints them — footer, contact page,
 * JSON-LD — must print the *same* strings. Divergent NAP is the usual reason a
 * local listing fails to consolidate.
 */
export const ORG = {
  name: "UFTECH.AI",
  legalName: "Unitforce Technologies Consulting Pvt Ltd",
  foundingYear: "2003",
  email: "info@uftech.com",
  phones: ["+91 8951 390 893", "+91 8951 003 881"],
  addressLocality: "Bengaluru",
  addressRegion: "Karnataka",
  addressCountry: "IN",
  areasServed: ["India", "United States", "United Kingdom", "United Arab Emirates", "Europe"],
  /* Profiles we control. `sameAs` is how a crawler ties this site to them and
     resolves them all to one entity — so only list accounts we actually own. */
  sameAs: [
    "https://uftech.com/",
    "https://uftech.in/",
    "https://www.linkedin.com/company/uftjobs/",
    "https://x.com/uftec",
    "https://www.facebook.com/uftjobs",
  ],
} as const;

export function absoluteUrl(path = "/"): string {
  return path === "/" ? SITE_URL : `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * The site-wide share card generated by app/opengraph-image.tsx.
 *
 * It has to be named explicitly: defining an `openGraph` object on a page
 * replaces the parent's wholesale, images included, so every page that set its
 * own title and description was silently shipping no og:image at all — which
 * is the difference between a link that previews as a card and one that
 * previews as a grey rectangle.
 */
const DEFAULT_OG_IMAGE = "/opengraph-image";

interface PageMetaInput {
  title: string;
  description: string;
  /** Route path, leading slash. Becomes both the canonical and the OG url. */
  path: string;
  /** Overrides the site-wide card for routes that generate their own. */
  image?: string;
  /** `article` for anything dated; everything on this site is a `website`. */
  type?: "website" | "article";
  /** Set on pages that exist for humans but add nothing to an index. */
  noindex?: boolean;
}

/**
 * Builds a page's metadata with a self-referencing canonical, which is the
 * point of the helper: without one, `/services/ai-copilots?utm_source=x` and
 * the clean URL are two documents competing for the same ranking.
 */
export function pageMetadata({
  title,
  description,
  path,
  image = DEFAULT_OG_IMAGE,
  type = "website",
  noindex = false,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);
  return {
    title,
    description,
    alternates: { canonical: url },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type,
      locale: "en_IN",
      images: [{ url: image, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [image],
    },
  };
}
